### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by mschneider82** [acouvreur/traefik-ondemand-service#13]
Hi, i have mostly finished the kubernetes support 

since "name" in the api is very less, i use the "name" value with an delimiter `_` to get all informations about the service

For Kubernetes the following informations are needed:

kind (e.g. deployment), namespace, name, replicacount(1)

```
        traefik-ondemand-plugin:
          name: deployment_namespace_application_1
          serviceUrl: 'http://traefik-ondemand-service:10000'
          timeout: 10m
```

Is this fine for a pull req?

edit: changed delimiter from * to _
