### ISSUE TITLE
-storagePath option is not working

### ISSUE THREAD

**Issue by flargargoyl** [acouvreur/traefik-ondemand-service#33]
having this as my compose:

```
  ondemand:
    image: ghcr.io/acouvreur/traefik-ondemand-service:1
    <<: *common-keys-core
    container_name: ondemand
    command: 
      - --swarmMode=false
      - --storagePath=/data/storage
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/ondemand:/data
```

container fails to start, with this error: 
flag provided but not defined: -storagePath
Usage of /go/bin/ondemand-service:
  -kubernetesMode
        Enable Kubernetes mode
  -swarmMode
        Enable swarm mode (default true)
        
Starts okay if -Storage Path not used in the configuration.
